name: CI

# Run this workflow every time a commit is pushed to main
on:
  push:
    branches:
      - az

jobs:
    build:
        name: Trigger "Publish Schema" pipeline on Azure DevOps.
        runs-on: ubuntu-latest
        steps:
        - name: Call Azure
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: 'https://dev.azure.com/CloudCompetenceCenter/Data Diensten'
            azure-pipeline-name: 'Deploy Mapserver' # name of the Azure pipeline to be triggered
            azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'